-- snowflake_setup.sql
-- Roles, warehouse, database, schemas, file format, stage, and RAW
-- table DDL for the Healthcare Revenue Cycle Analytics project.
-- Run this as ACCOUNTADMIN (or a role with sufficient privileges)
-- in a Snowsight worksheet.

-- 1. WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS HEALTHCARE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for healthcare RCM analytics portfolio project';

-- 2. ROLES
CREATE ROLE IF NOT EXISTS HEALTHCARE_LOADER;
CREATE ROLE IF NOT EXISTS HEALTHCARE_TRANSFORMER;
CREATE ROLE IF NOT EXISTS HEALTHCARE_BI_READER;

SET my_user = CURRENT_USER();
GRANT ROLE HEALTHCARE_LOADER TO USER IDENTIFIER($my_user);
GRANT ROLE HEALTHCARE_TRANSFORMER TO USER IDENTIFIER($my_user);
GRANT ROLE HEALTHCARE_BI_READER TO USER IDENTIFIER($my_user);

GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE HEALTHCARE_LOADER;
GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE HEALTHCARE_TRANSFORMER;
GRANT USAGE ON WAREHOUSE HEALTHCARE_WH TO ROLE HEALTHCARE_BI_READER;

-- 3. DATABASE + SCHEMAS
CREATE DATABASE IF NOT EXISTS HEALTHCARE_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ANALYTICS.RAW_HEALTHCARE
  COMMENT = 'Immutable, source-aligned landing zone loaded by Python/COPY INTO';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ANALYTICS.ANALYTICS_DEV
  COMMENT = 'dbt development target - staging/intermediate/marts while building';
CREATE SCHEMA IF NOT EXISTS HEALTHCARE_ANALYTICS.ANALYTICS_PROD
  COMMENT = 'dbt production target - published marts for Power BI';

GRANT OWNERSHIP ON SCHEMA HEALTHCARE_ANALYTICS.RAW_HEALTHCARE TO ROLE HEALTHCARE_LOADER COPY CURRENT GRANTS;
GRANT ALL ON SCHEMA HEALTHCARE_ANALYTICS.RAW_HEALTHCARE TO ROLE HEALTHCARE_TRANSFORMER;
GRANT OWNERSHIP ON SCHEMA HEALTHCARE_ANALYTICS.ANALYTICS_DEV TO ROLE HEALTHCARE_TRANSFORMER COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA HEALTHCARE_ANALYTICS.ANALYTICS_PROD TO ROLE HEALTHCARE_TRANSFORMER COPY CURRENT GRANTS;
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS TO ROLE HEALTHCARE_LOADER;
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS TO ROLE HEALTHCARE_TRANSFORMER;
GRANT USAGE ON DATABASE HEALTHCARE_ANALYTICS TO ROLE HEALTHCARE_BI_READER;
GRANT USAGE ON SCHEMA HEALTHCARE_ANALYTICS.ANALYTICS_PROD TO ROLE HEALTHCARE_BI_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA HEALTHCARE_ANALYTICS.ANALYTICS_PROD TO ROLE HEALTHCARE_BI_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA HEALTHCARE_ANALYTICS.ANALYTICS_PROD TO ROLE HEALTHCARE_BI_READER;

USE ROLE HEALTHCARE_LOADER;
USE WAREHOUSE HEALTHCARE_WH;
USE DATABASE HEALTHCARE_ANALYTICS;
USE SCHEMA RAW_HEALTHCARE;

-- 4. FILE FORMAT
CREATE FILE FORMAT IF NOT EXISTS RAW_HEALTHCARE.FF_CSV_STANDARD
  TYPE = 'CSV'
  FIELD_DELIMITER = ','
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('', 'NULL', 'null', 'NaN')
  EMPTY_FIELD_AS_NULL = TRUE
  TRIM_SPACE = TRUE
  ENCODING = 'UTF8';

-- 5. INTERNAL STAGE
CREATE STAGE IF NOT EXISTS RAW_HEALTHCARE.STG_CSV_LOAD
  FILE_FORMAT = RAW_HEALTHCARE.FF_CSV_STANDARD
  COMMENT = 'Internal stage the Python ingestion script PUTs CSVs into before COPY INTO';

-- 6. RAW TABLES (VARCHAR-typed; casting happens in dbt staging)
CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.PATIENTS (
    patient_id VARCHAR, first_name VARCHAR, last_name VARCHAR, dob VARCHAR,
    age VARCHAR, gender VARCHAR, ethnicity VARCHAR, insurance_type VARCHAR,
    marital_status VARCHAR, address VARCHAR, city VARCHAR, state VARCHAR,
    zip VARCHAR, phone VARCHAR, email VARCHAR, registration_date VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.PROVIDERS (
    provider_id VARCHAR, name VARCHAR, department VARCHAR, specialty VARCHAR,
    npi VARCHAR, inhouse VARCHAR, location VARCHAR, years_experience VARCHAR,
    contact_info VARCHAR, email VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.ENCOUNTERS (
    encounter_id VARCHAR, patient_id VARCHAR, provider_id VARCHAR, visit_date VARCHAR,
    visit_type VARCHAR, department VARCHAR, reason_for_visit VARCHAR, diagnosis_code VARCHAR,
    admission_type VARCHAR, discharge_date VARCHAR, length_of_stay VARCHAR,
    status VARCHAR, readmitted_flag VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.DIAGNOSES (
    diagnosis_id VARCHAR, encounter_id VARCHAR, diagnosis_code VARCHAR,
    diagnosis_description VARCHAR, primary_flag VARCHAR, chronic_flag VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.PROCEDURES (
    procedure_id VARCHAR, encounter_id VARCHAR, procedure_code VARCHAR,
    procedure_description VARCHAR, procedure_date VARCHAR, provider_id VARCHAR,
    procedure_cost VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.CLAIMS_AND_BILLING (
    billing_id VARCHAR, patient_id VARCHAR, encounter_id VARCHAR, insurance_provider VARCHAR,
    payment_method VARCHAR, claim_id VARCHAR, claim_billing_date VARCHAR,
    billed_amount VARCHAR, paid_amount VARCHAR, claim_status VARCHAR, denial_reason VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

CREATE TABLE IF NOT EXISTS RAW_HEALTHCARE.DENIALS (
    claim_id VARCHAR, denial_id VARCHAR, denial_reason_code VARCHAR,
    denial_reason_description VARCHAR, denied_amount VARCHAR, denial_date VARCHAR,
    appeal_filed VARCHAR, appeal_status VARCHAR, appeal_resolution_date VARCHAR, final_outcome VARCHAR,
    _source_file VARCHAR, _loaded_at TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
  );

-- 7. COPY INTO TEMPLATE (Python script issues these per file at load
--    time; kept here for manual reference/reruns)
-- COPY INTO RAW_HEALTHCARE.PATIENTS (patient_id, first_name, last_name, dob, age, gender,
--   ethnicity, insurance_type, marital_status, address, city, state, zip, phone, email,
--   registration_date, _source_file)
-- FROM (SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16, METADATA$FILENAME
--       FROM @RAW_HEALTHCARE.STG_CSV_LOAD/patients.csv.gz)
-- FILE_FORMAT = (FORMAT_NAME = RAW_HEALTHCARE.FF_CSV_STANDARD)
-- ON_ERROR = 'ABORT_STATEMENT';

GRANT SELECT ON ALL TABLES IN SCHEMA RAW_HEALTHCARE TO ROLE HEALTHCARE_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RAW_HEALTHCARE TO ROLE HEALTHCARE_TRANSFORMER;
