name: 'healthcare_analytics'
version: '1.0.0'
config-version: 2

profile: 'healthcare_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  healthcare_analytics:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      core:
        +schema: marts
        +materialized: table
      business:
        +schema: marts
        +materialized: table

vars:
  raw_database: "HEALTHCARE_ANALYTICS"
  raw_schema: "RAW_HEALTHCARE"
